### ISSUE TITLE
The expand modifier doesn't work on Image selections

### ISSUE THREAD

**Issue by xavigu42** [SigmaHQ/pySigma-backend-crowdstrike#14]
Hi guys,

Unsure if this is the right repo or I'd need to open an issue with pySigma directly. I apologize in advance.

https://sigmahq.io/docs/basics/modifiers.html#expand

We were testing the use of the `expand` modifier to make our rules a bit more generic and to ease the maintenance. This would be beneficial for the many DNS/network rules we have at the moment to monitor RRM tools, exfiltration to cloud storage services, etc..

At the moment we need to copy and paste the list of browser binaries in the filters.

I our setup we have observed the following behavior....

What works:

```
QueryName|expand: "%dodgy_websites%"
```

What doesn't work:
```
Image|expand: "%browser_binaries%"
```

**Comment by moullos** [comment]
@xavigu42 you can try a different backend/pipeline and let me know if the issue persists? That should tell us if the issue is with with the backend/pipeline or pysigma

**Comment by xavigu42** [comment]
Hi guys,

I did a quick test  with the CrowdSrike and Splunk pipelines. To do so, I had to comment out a Processor that validates the `Image` field, so I could bypass the error `Only file name of image is available in CrowdStrike Query Language events`

See: https://github.com/SigmaHQ/pySigma-backend-crowdstrike/blob/77e0158ad5cc276577e508ad0e38d9f9134b5d1a/sigma/pipelines/crowdstrike/crowdstrike.py#L416

```
+#        # ContextBaseFileName handling
+#        ProcessingItem(
+#            identifier="cql_contextbasefilename_fail_completepath",
+#            transformation=DetectionItemFailureTransformation(
+#                "Only file name of image is available in CrowdStrike Query Language events."
+#            ),
+#            field_name_conditions=[
+#                cond_field_contextbasefilename,
+#            ],
+#            detection_item_conditions=[
+#                MatchStringCondition(
+#                    cond="any",
+#                    pattern="^\\*\\\\?[^\\\\]+$",
+#                    negate=True,
+#                ),
+#            ],
+#        ),
```

pyproject.toml:

```
python = "^3.8"
pysigma = "^0.11.3"
sigma-cli = "^1.0.4"
```

Sigma rule snippet:
```
    browsers:
      Image|expand: '%web_browsers%'
    condition: 1 of selection_* and not browsers
```

CrowdStrike pipeline:
```
poetry run  -C / sigma convert -t log_scale  \
-p  crowdstrike_fdr -p sigma/templates/dns_query.yml \
--filter sigma/filters/common/dns_query/dns_query_win_remote_access_software_domains_non_browsers.yml \
sigma/rules/common/dns_query/dns_query_win_remote_access_software_domains_non_browsers.yml
```

Generates:

```
 not ContextBaseFileName=/^%web_browsers%$/i
```

Splunk pipeline:

```
poetry run  -C / sigma convert -t  splunk \
-p sigma/templates/dns_query.yml \
--filter sigma/filters/common/dns_query/dns_query_win_remote_access_software_domains_non_browsers.yml  \
sigma/rules/common/dns_query/dns_query_win_remote_access_software_domains_non_browsers.yml
```

Generates:
```
 NOT (Image IN ("chrome.exe", "firefox.exe", "iexplore.exe", "MicrosoftEdge.exe", "msedge.exe", "msedgewebview2.exe", "safari.exe", "MsMpEng.exe", "MsSense.exe", "brave.exe", "opera.exe", "seamonkey.exe", "vivaldi.exe"))
```

**Comment by moullos** [comment]
@thomaspatzke I might need your help with this, as I am able to replicate it but can't figure out the root cause.

To replicate:

- Test pipeline

```
name: value_placeholder_pipeline
vars:
  test_list: 
  - val1
  - val2
transformations:
  - type: value_placeholders
```

- Test rule
```
title: Expand Test with dns query
status: test
logsource:
    category: dns_query
    product: windows
detection:
    sel:
        Image|expand: "%test_list%"
    condition: sel
```

Tested with:
``` sigma convert -t log_scale -p ./test_pipeline.yml -p crowdstrike_fdr .\test_rule.yml ```

As @xavigu42 pointed out, this works fine for fields without transformations.

- Working rule
```
title: Working rule
status: test
logsource:
    category: dns_query
    product: windows
detection:
    sel:
        QueryName|expand: "%test_list%"
    condition: sel
```
